### ISSUE TITLE
Display custom headers in Compose

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#2582]
The user can add user-defined headers to outgoing mail using the `my_hdr` command,
or by setting `$edit_headers` and adding them manually in their editor.

These are stored in the global `UserHeader`.

I suggest adding the fields after the security info:

```
    From:
      To:
      Cc:
     Bcc:
 Subject:
Reply-To:
     Fcc:
Security:
 Headers: X-Company: Acme
          X-Website: https://acme.com
```

The drawing of the Compose screen is done in two stages:
- `calc_envelope()` - Calculate how much space is needed
- `draw_envelope()` - Perform the actual drawing

Add a call to each to calculate and draw the user headers.
