### ISSUE TITLE
Compose menu: "Encrypt with:" overrides `(OppEnc mode)` text

### ISSUE THREAD

**Issue by whitney-cumber** [neomutt/neomutt#3695]
## Expected Behaviour

No trunction in the `Security:` header line of the compose menu

## Actual Behaviour

The (top part of the) compose menu looks like

```
        From: me@example.org
          To: foo@example.org
          Cc:
         Bcc:
     Subject: Whatever
    Reply-To:
         Fcc: =sent
    Security: Encrypt (S/MIME) (OppEnc mEncrypt with: aes256
```

Note the trunctation of `(OppEnc mode)` to `(OppEnc m`.

## Steps to Reproduce

Use opportunistic encryption together with S/MIME, e.g. this neomuttrc-oppenc-smime

```
set crypt_opportunistic_encrypt = yes
set smime_is_default = yes

# Set up your S/MIME backend for your system properly (we use GPGME)
set crypt_use_gpgme = yes

# only for convenience, to have one prompt less to describe
set auto_edit = yes
set edit_headers = yes
```

0. `neomutt -F neomuttrc-oppenc-smime -- foo@example.org`
   **Important**: you need the certificate for foo@example.org in order for opportunistic encryption to kick in and encrypt the message.
1. Save and quit editor (possibly answering some prompts beforehand)
2. Back in the compose menu, see the line for Security
```
Security: Encrypt (S/MIME) (OppEnc mEncrypt with: aes256
```
The "(OppEnc mode)" is truncated

## Suggestion

Place `Encrypt with:` header in a separate line like `Sign as:` (I never understood why this wasn't the case.)

## NeoMutt Version

```
20220429-371-e26e9d
```
