### ISSUE TITLE
Security header misalignment in compose view

### ISSUE THREAD

**Issue by grobian** [neomutt/neomutt#48]
Using neomutt-20160611 Gentoo branch patches on 1.6.1 release

compose view looks like this for me:
```
        From: Fabian Groffen <grobian@gentoo.org>
          To: Richard Russon <rich@flatcap.org>
          Cc:
         Bcc:
     Subject: Re: NeoMutt 2016-06-11
    Reply-To:
         Fcc: imaps://user@imap/Gentoo
Security:  sign als: 0xC5C74E89
```

I'll hunt later when I have some time.
